"""added savings to user

Revision ID: 1152dcc7f6df
Revises: a757914543ac
Create Date: 2025-12-12 19:54:47.001696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1152dcc7f6df'
down_revision: Union[str, Sequence[str], None] = 'a757914543ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('savings', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'savings')
    # ### end Alembic commands ###
